Description: This template deploys networking components for our different applications hosted in the cloud environment.

Parameters:
    BaseInfrastructure:
        Description: This name will be prefixed to all the resources in the stack.
        Type: String

    VpcCIDR:
        Description: CIDR IP range for our VPC
        Type: String
        Default: 10.0.0.0/16

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: !Ref BaseInfrastructure

       #Internet Gateway that provides access for the resources within VPC

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Ref BaseInfrastructure

    # Attachment of Internset Gateway to VPC

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC