AWSTemplateFormatVersion: 2010-09-09
Description: This template defines a single Amazon EC2 instance with a security group that allows SSH traffic on port 22 and HTTP traffic on port 80 on Linux Virtual Machine.

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name

  EnvironmentType:
    Description: 'defines the environment type for your stack'
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  InstanceImageId:
    Description: EC2 Image Id from this region
    Type: AWS::EC2::Image::Id
    Default: ami-0aa7d40eeae50c9a9 # defaults for amazon linux in us-east-1 region

  KeyPairName:
    Type: String
    Description: The name of an existing Amazon EC2 key pair in this region to use to SSH into the Amazon EC2 instances.

  SSHLocation:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: The IP address range that can be used to access the web server using SSH.
    MaxLength: '18'
    MinLength: '9'
    Type: String

Mappings:
  EnvironmentToInstanceType:
    dev:
      InstanceType: t2.micro
    test:
      InstanceType: t2.nano
    prod:
      InstanceType: t2.small

Resources:
  webserverSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '-', [ webserver-sg, dev ] ]
      GroupDescription: 'Allow access on ports 80 ,443 and 22'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

      VpcId: vpc-0198c952ea1569a2d
      Tags:
        - Key: Name
          Value: webserver SG

  webserver:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: !Ref AvailabilityZone
        ImageId: !Ref InstanceImageId  # ImageID valid only in us-east-1 region
        InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref EnvironmentType, InstanceType]
        SubnetId: subnet-0150de60ee1a447c1
        KeyName: !Ref KeyPairName 
        SecurityGroupIds:
          - !Ref webserverSG
        Tags:
          - Key: Name
            Value: demo-server

 