AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an RDS instance with PostgreSQL 13.7 engine 

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - 
        Label: 
          default: Database Parameters
        Parameters:
          - DBInstanceIdentifier
          - DBName
          - DBUser
          - DBPassword
          - DBBackupRetentionPeriod
          - DBAllocatedStorage
          - DBInstanceClass
          - MultiAZDatabase

Parameters:

  DBInstanceIdentifier:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: postgresqldb
    Description: Instance identifier name
    MaxLength: 60
    MinLength: 1
    Type: String

  DBName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: applicationdb
    Description: postgresql database name
    MaxLength: 64
    MinLength: 1
    Type: String

  DBUser:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: dbadmin
    Description: Username for postgresql database access
    MaxLength: 16
    MinLength: 1
    NoEcho: true
    Type: String

  DBPassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters
    Default: test1234
    Description: Password for PostgreSQL database access
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String

  DBBackupRetentionPeriod:
    ConstraintDescription: Database backup retention period must be between 0 and 35 days
    Default: 0
    Description: The number of days for which automatic DB snapshots are retained
    MaxValue: 35
    MinValue: 0
    Type: Number

 
  DBAllocatedStorage:
    ConstraintDescription: Must be between 5 and 1024Gb
    Default: 20
    Description: The size of the database (Gb)
    MaxValue: 1024
    MinValue: 5
    Type: Number


  DBInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
    ConstraintDescription: Must be a valid database instance type
    Default: db.t2.micro
    Description: The database instance type
    Type: String

  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be either true or false
    Default: false #choose true value for production environment
    Description: Creates a Multi-AZ postgreSQL Amazon RDS db instance
    Type: String

Resources:   

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DatabaseAllocatedStorage
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBInstanceIdentifier: !Ref DatabaseInstanceIdentifier
      DBName: !Ref DatabaseName
      Engine: PostgreSQL
      EngineVersion: 13.7
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      MultiAZ: !Ref MultiAZDatabase
